### ISSUE TITLE
CodeBuild AccountLimitExceededException when building aft

### ISSUE THREAD

**Issue by louislarry** [aws-ia/terraform-aws-control_tower_account_factory#100]
I made a terraform repo with following main.tf:

```terraform
module "aft" {
  source = "github.com/aws-ia/terraform-aws-control_tower_account_factory"

  aft_management_account_id = "xxxx"
  ct_management_account_id  = "xxxx"
  audit_account_id          = "xxxx"
  log_archive_account_id    = "xxxx"

  ct_home_region              = "ap-southeast-1"
  tf_backend_secondary_region = "us-east-1"

  vcs_provider = "github"
}
```

When I run `terraform apply`, it spits out following error:
```shell
│ Error: Lambda function (aft-lambda-layer-codebuild-invoker) returned error: ({"errorMessage": "An error occurred (AccountLimitExceededException) when calling the StartBuild operation: Cannot have more than 0 builds in queue for the account", "errorType": "AccountLimitExceededException", "stackTrace": ["  File \"/var/task/codebuild_invoker.py\", line 30, in lambda_handler\n    job_id = client.start_build(projectName=codebuild_project_name)[\"build\"][\"id\"]\n", "  File \"/var/runtime/botocore/client.py\", line 386, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 705, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]})
│ 
│   with module.aft.module.aft_lambda_layer.data.aws_lambda_invocation.invoke_codebuild_job,
│   on .terraform/modules/aft/modules/aft-lambda-layer/lambda.tf line 21, in data "aws_lambda_invocation" "invoke_codebuild_job":
│   21: data "aws_lambda_invocation" "invoke_codebuild_job" {
│ 
```

Every time I tried to "Start build" in the console, it refuses:

> Build failed to Start. The following error occurred: Cannot have more than 0 builds in queue for the account

Log events from CloudWatch:

```
[ERROR]	2022-02-27T01:01:56.498Z	5aaae098-f77f-457d-8ff8-ee202b27c308	{'FILE': 'codebuild_invoker.py', 'METHOD': 'lambda_handler', 'EXCEPTION': 'An error occurred (AccountLimitExceededException) when calling the StartBuild operation: Cannot have more than 0 builds in queue for the account'}
Traceback (most recent call last):
  File "/var/task/codebuild_invoker.py", line 30, in lambda_handler
    job_id = client.start_build(projectName=codebuild_project_name)["build"]["id"]
  File "/var/runtime/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.AccountLimitExceededException: An error occurred (AccountLimitExceededException) when calling the StartBuild operation: Cannot have more than 0 builds in queue for the account

[ERROR] AccountLimitExceededException: An error occurred (AccountLimitExceededException) when calling the StartBuild operation: Cannot have more than 0 builds in queue for the account
Traceback (most recent call last):
  File "/var/task/codebuild_invoker.py", line 30, in lambda_handler
    job_id = client.start_build(projectName=codebuild_project_name)["build"]["id"]
  File "/var/runtime/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

**Comment by louislarry** [comment]
This is an AWS account permission issue. I tested in a different AWS account and it worked. Closing the issue.

**Comment by aravindkoniki** [comment]
@louislarry  I have the same issue when Im trying to deploy in "aft management account"  getting the same error as you get

how did you resolve ? Seen you comment that you have tested on another account

**Comment by willmitchell** [comment]
For others who may arrive here wondering what to do about an error such as the one shown below, I will explain what is happening.

`Build failed to Start. The following error occurred: Cannot have more than 0 builds in queue for the account`

Even if Service Quotas shows your limits as >0, there are hidden quotas that are associated with fraud and abuse prevention.  When you create a new account (such as AFT-Management) and then try to launch a bunch of resources in it, you can get tripped up by these fraud prevention controls in the manner shown above.

I created a support case for this error, and the support engineer suggested that I launch 10 t2.micro instances and let them run for 4 hours.  This will cause the hidden fraud prevention limits to be scaled back, which should enable this overall solution to run.

The instances are launching now.  I had to write a script to launch them separately, because, again fraud prevention mechanisms prevented me from launching 10 at once via the console.  I will report back later today with results.

**Comment by willmitchell** [comment]
Well, after about 90 minutes, I tried terraform plan and it worked.  So this confirm that, at least in my case, the AccountLimitExceededException was due to fraud prevention controls (aka Service Limits).
