### ISSUE TITLE
How do I turn of the default AFT PrivateLink and VPC settings. 

### ISSUE THREAD

**Issue by mbuotidem** [aws-ia/terraform-aws-control_tower_account_factory#127]
The AFT pricing page says "You can change these default settings for AFT" when discussing the fact that the default setup uses AWS PrivateLink endpoints and a NAT gateway. However, I'm unable to find anywhere in the documentation where I can learn how to change these default settings. Please could you point me towards that? Thanks

**Comment by balltrev** [comment]
Hey @mbuotidem, I think the README.md has the configuration you're looking for:
https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main#input_aft_vpc_endpoints

I believe during deployment you specify false for the `aft_vpc_endpoints` input, however AFT requires NAT Gateways due to the use of CodeBuild within a VPC

**Comment by mbuotidem** [comment]
Thank you!

**Comment by jensenbox** [comment]
In an effort to keep costs to a minimum, I would prefer to be able to supply my own RAM shared subnets instead of crafting a totally new set of NAT Gateways. Is there any way this could be done? I rather not spend an extra $90 month for something that is very rarely used - meaning CodeBuild is executed infrequently.
