### ISSUE TITLE
Modules fail to be used from the terraform folder in account customisations

### ISSUE THREAD

**Issue by ChrisMusgrove** [aws-ia/terraform-aws-control_tower_account_factory#135]
Hi,

Is it possible to use modules within the account customisations stage? Whenever we try to call them from the file (e.g. ../../module/ssm) the pipeline fails stating it cannot see a module. Outside of AFT this terraform works.

Kind regards,
Chris

**Comment by snebhu3** [comment]
@ChrisMusgrove thank you for reaching out.
Please may you elaborate and provide more information on your specific implementation, and which pipeline and stage you are facing the issue so that we could try to reproduce it on our side.

Also, please find the [AWS documentation for implementation of account customization](https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html#aft-global-customizations) for reference.

**Comment by balltrev** [comment]
Feel free to get back to us with more information here @ChrisMusgrove, going to close this issue in the mean time.
