### ISSUE TITLE
AFT feature option "aft-delete-default-vpc" does not delete default vpc in all regions

### ISSUE THREAD

**Issue by jcchenn** [aws-ia/terraform-aws-control_tower_account_factory#142]
**Terraform Version & Prov:**
1.1.6

**AFT Version:**
1.3.5

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
Terraform v1.1.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

`terraform providers`
```
terraform providers

Providers required by configuration:
.
└── module.aft
    ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_feature_options
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── module.packaging
    │   └── provider[registry.terraform.io/hashicorp/archive]
    ├── module.aft_code_repositories
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_ssm_parameters
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── module.aft_account_provisioning_framework
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── module.aft_customizations
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_account_request_framework
    │   ├── provider[registry.terraform.io/hashicorp/time]
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── module.aft_backend
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    ├── module.aft_iam_roles
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
    │   ├── module.aft_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 2.7.0
    │   ├── module.audit_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 2.7.0
    │   ├── module.ct_management_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 2.7.0
    │   └── module.log_archive_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 2.7.0
    └── module.aft_lambda_layer
        ├── provider[registry.terraform.io/hashicorp/aws] >= 3.72.0, < 4.0.0
        ├── provider[registry.terraform.io/hashicorp/random]
        └── provider[registry.terraform.io/hashicorp/local]

Providers required by state:
    provider[registry.terraform.io/hashicorp/archive]
    provider[registry.terraform.io/hashicorp/local]
    provider[registry.terraform.io/hashicorp/random]
    provider[registry.terraform.io/hashicorp/time]
    provider[registry.terraform.io/hashicorp/aws]
```

**Bug Description**
Set "aft_feature_delete_default_vpcs_enabled = true" in bootstrap file, after enroll the new account, only default vpc in control tower home region is deleted, the default vpc in all other region still remain. 

**To Reproduce**
1. Enroll a new account via push account request tf file into repo
2. After account enroll completed, login into the new account enrolled in step above
3. Check on the vpc for Control Tower home region and all other regions, you will notice only default vpc in Control Tower home region is deleted, all other region still have default vpc.

**Expected behavior**
The default vpc on all regions should be deleted. 

**Additional context**
It seems this is a small bug at line of 81 and 82 in "aft_delete_default_vpc.py", 

                session = boto3.session.Session(region_name=region)
                client = session.client("ec2")

I suspect the session was overwritten, since it is running in a loop, hence, after delete the first default vpc, the session is not able to be created in other region, I changed the code to below:

                #session = boto3.session.Session(region_name=region)
                client = session.client("ec2", region_name=region)

 And also at line 85 to 87, I changed to 

                    resource: EC2ServiceResource = session.resource(
                        "ec2", region_name=region
                    )

Both changes is to keep using the session variable that created before the "for region in regions:" loop. I tested after the change and it works fine, the default vpc for all regions of new enrolled account are deleted. 

There is another small cosmetic bug in feature_options.py at line 87, the log message is using "SGs", it should be:
                 logger.info("IGWs: " + str(igws))

**Comment by balltrev** [comment]
Hey @jcchenn, I think we were able to reproduce this bug. I've gone ahead and created a backlog to address this with the team, thanks!

**Comment by adam-daily** [comment]
Hey there, sorry for the delay in updating.

We've become aware of an issue wherein the Delete Default VPCs feature option is not behaving in a manner that is consistent with AFT documentation. The documentation communicated that the feature option should delete default VPCs in all accounts managed by AFT. In reality AFT deletes default VPCs within the AFT management account, but not in accounts that AFT manages.

While a change to update the behavior to delete VPCs in all AFT vended accounts is relatively straightforward, we've deemed it risky to update to this behavior at this time. Customers have enrolled existing accounts in AFT and have not seen their default VPCs deleted with this feature enabled. Changing the behavior of the feature option to delete those default VPCs could put those customers at risk.

To alleviate the immediate miscommunication, [we've updated the AFT docs to reflect the actual behavior](https://docs.aws.amazon.com/controltower/latest/userguide/aft-feature-options.html#delete-default-vpc-option). We're exploring other options for how to introduce functionality to delete default VPCs in vended accounts in a manner that is safe for our customers. In the meantime, the Control Tower service itself will delete default VPCs in accounts you vend in regions managed by Control Tower. You can read more about this process [here](https://docs.aws.amazon.com/controltower/latest/userguide/configure-without-vpc.html).

We apologize for the inconvenience caused by this miscommunication. Further updates to this behavior will be communicated on the AFT GitHub page and through public AWS documentation.

**Comment by laminarcode** [comment]
>Customers have enrolled existing accounts in AFT and have not seen their default VPCs deleted with this feature enabled. Changing the behavior of the feature option to delete those default VPCs could put those customers at risk.

Would customers who are desiring to use their default VPC leave this feature disabled? 
Conversely: Is the customers action to manually set this feature flag to enable not a sufficient expression of intent to delete default VPCs?

Additionally: VPCs which are in-use (have resources such as elastic-interfaces or security groups) will fail to delete until those dependent resources are deleted first. So even if this feature were to suddenly try to delete default VPCs, those VPCs which are in-use would remain.
