### ISSUE TITLE
Ability to target different branch for customizing an AWS account

### ISSUE THREAD

**Issue by pmmalinov01** [aws-ia/terraform-aws-control_tower_account_factory#146]
**Describe the outcome you'd like**

As we develop more code around AFT we found ourselves in the situation to push code into the main branch that we are not 100% sure will work correctly or even at all. It will be great if we could re-run a pipeline with a target to a specific git branch, that will be used for test and verification. The use of different branches other than the main will prevent other pipelines from breaking while some engineer is doing his task.

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

Lack of ability to test and verify code before merging in main branch.

**Additional context**

As an example:
We are developing a module for AWS SecurityHub to manage and enable the service. This feature will be rolled out to all accounts so it will be placed in global customization. But if it is placed in the main branch some re-runs or future deployed accounts will run the code that may or may not be still in active development. It would be much easier to keep the code in a branch `foo` and allow to rerun it via the StepFunction like
```
{
  "include": [
    {
      "type": "accounts",
      "target_value": [ "acc1_ID","acc2_ID"]
      "git_ref": "foo"
    }
  ]
}
```

**Comment by balltrev** [comment]
Hey @pmmalinov01, AFT was designed as a deployment tool for Terraform-based customizations in Control Tower managed accounts, but isn't opinionated about the development/test/release process prior to that deployment, and that's by design because customers' release workflows differ so greatly.

One recommendation would be to develop Terraform modules externally to AFT, and only using AFT to deploy them once those modules have passed your testing.

To the example, once you've passed local testing of the Terraform modules, you could use account level customizations to deploy Terraform modules under active development, promoting to global customizations after testing is successful.
