### ISSUE TITLE
Account Provisioning Customizations Concurrency Question/Bug?

### ISSUE THREAD

**Issue by SizZiKe** [aws-ia/terraform-aws-control_tower_account_factory#155]
**Terraform Version & Prov:** 1.1.9

**AFT Version:** 1.3.6

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
1.1.9
```

`terraform providers`
```
aws 4.13.0
```

**Bug Description**
When updating accounts with a new custom_field, AFT invoked the `aft-provisioning-customizations` step function immediately for each account, so they are all concurrent. Is this expected?

**To Reproduce**
1. Update multiple accounts with a new/modified custom_field
2. Watch the `aft-provisioning-customizations` step function get invoked once for each modification.

**Expected behavior**
My expectation is that `aft-provisioning-customizations` would get invoked with a maximum concurrency of one.

**Related Logs**
Provide any related logs or error messages to help explain your problem.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/6923208/168171039-0dea578b-e791-4f47-b415-8a8691767d46.png">

**Additional context**

**Comment by snebhu3** [comment]
@SizZiKe when you update custom fields, this will eventually invoke the aft-account-provisioning-framework step function for each account, which in one of its steps invokes the aft-account-provisioning-customizations steps function for respective account. It is an expected behavior that the aft-account-provisioning-framework step function executions could be invoked in parallel for the AFT managed accounts, these are not set up to run serially for each account.
