### ISSUE TITLE
Account Provisioning Customizations and Global/Account Customizations Concurrency Question/Bug?

### ISSUE THREAD

**Issue by SizZiKe** [aws-ia/terraform-aws-control_tower_account_factory#156]
**Terraform Version & Prov:** 1.1.9

**AFT Version:** 1.3.6

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
1.1.9
```

`terraform providers`
```
aws 4.13.0
```

**Bug Description**
When updating accounts with a new custom_field, AFT invoked the `aft-provisioning-customizations` step function immediately for each account, and each of the global/account provisioning customization pipelines were invoked for each respective account at the same time provisioning customizations was running.

**To Reproduce**
1. Update multiple accounts with a new/modified custom_field
2. Watch the `aft-provisioning-customizations` step function get invoked once for each modification.
3. Watch each global/account customization pipeline get invoked at the same time as the corresponding run for aft-provisioning-customizations.

**Expected behavior**
My expectation is that global/account pipelines would run after the aft-provisioning-customizations step function.

**Related Logs**
Provide any related logs or error messages to help explain your problem.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/6923208/168171341-466180f7-e476-4547-bd9f-77de99e5882e.png">
<img width="501" alt="image" src="https://user-images.githubusercontent.com/6923208/168171532-e3a3c18e-7742-47cd-b067-a63d468031a6.png">

**Additional context**

**Comment by snebhu3** [comment]
@SizZiKe when you update custom fields, this will eventually invoke the `aft-account-provisioning-framework` step function for each account, which in one of its steps invokes the `aft-account-provisioning-customizations` steps function for each respective account, and in another step creates the `<acc-id>-customizations-pipeline` for respective account if not already present. It is an expected behavior that the `aft-account-provisioning-framework` step function executions could be invoked in parallel for the AFT managed accounts, these are not set up to run serially for each account. 

The `<acc-id>-customizations-pipeline` which apply the global and account level customizations are not invoked automatically, these need to be invoked separately by you via `aft-invoke-customizations` step function targeting respective managed accounts as per your deployment strategy. 

Please can you confirm if this is the behavior you are seeing in your environment? `<acc-id>-customizations-pipeline` should not be invoked automatically ideally.
