### ISSUE TITLE
Terraform providers: allow using alternative IAM entities for deploying AFT

### ISSUE THREAD

**Issue by theipster** [aws-ia/terraform-aws-control_tower_account_factory#191]
**Describe the outcome you'd like**

Allow consumers of this module (`github.com/aws-ia/terraform-aws-control_tower_account_factory`) to configure the IAM entities used for deploying AFT (**note**: AFT itself, not the accounts, etc.).

In other words, allow the following:

```tf
# foo-workspace/aft.tf
module "aft" {
  source = "github.com/aws-ia/terraform-aws-control_tower_account_factory"

  providers = {
    aws.aft_management              = aws.aft_management
    aws.audit                       = aws.audit
    aws.ct_management               = aws.ct_management
    aws.log_archive                 = aws.log_archive
    aws.tf_backend_secondary_region = aws.tf_backend_secondary_region
  }

  # Required vars
  aft_management_account_id   = ...
  audit_account_id            = ...
  ct_home_region              = ...
  ct_management_account_id    = ...
  log_archive_account_id      = ...
  tf_backend_secondary_region = ...
}

# foo-workspace/provider.tf
provider "aws" {
  alias  = "ct_management"
  region = var.ct_home_region

  assume_role {
    role_arn = <my custom IAM role in CT management account>
  }
}

provider "aws" {
  alias  = "aft_management"
  region = var.ct_home_region

  assume_role {
    role_arn = <my custom IAM role in AFT management account>
  }
}

provider "aws" {
   ...
}
```

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

Two key problems, both around the execution context (CI/CD, not manual deployment):

1. #### IAM roles, not IAM users.
    
    Our CI/CD model is based entirely around using IAM roles (assumed by IAM users) for execution, rather than using IAM users directly.

    This is for a) better separation of concerns, and b) for a consistent method of cross-account access for all our deployments in general. As such, we intentionally restrict IAM users' permissions to least-privilege, since the IAM roles do all the heavy lifting anyway.
    
    However, the `aws.ct_management` provider [makes an unnecessary assumption](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.4.2/providers.tf#L7) that the current execution environment is sufficiently authorized to deploy resources. In our case, it (the IAM user) can't.

    A simple solution would be to allow an IAM role to be assumed for the `aws.ct_management` provider.

 2. #### Dedicated deployment account, not CT account.

    Our CI/CD model keeps all deployment IAM users in a dedicated deployment account (separation of concerns, similar to having a Deployment OU as recommended [here](https://aws.amazon.com/blogs/mt/best-practices-for-organizational-units-with-aws-organizations/)). This dedicated deployment account is obviously _not_ the CT management account.

    This causes a problem - not only with the `aws.ct_management` provider (as above) but also with all the other `aws` providers too, because they are all [hardcoded](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.4.2/providers.tf#L19) to assume their respective accounts' CT-provisioned `AWSControlTowerExecution` role, which **only** trusts the CT account.

    Again, a simple solution would be to allow an alternative IAM role to be assumed for these `aws` providers. The role would be granted the same `AdministratorAccess` permissions (or otherwise... as per #111), but would trust the _deployment account_ instead of the CT account.

**Additional context**

#### Technical direction
It seems like some thought has already been put into this previously, given that `configuration_aliases` have already [been defined](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.4.2/versions.tf#L11).

It also meets Terraform best practices in terms of not declaring `provider` blocks within a module that is intended to be called by others:

> A module intended to be called by one or more other modules must not contain any provider blocks.
> 
> _Source: https://www.terraform.io/language/modules/develop/providers_

#### Ease of implementation

The only code change required to implement this is: to delete the existing [`provider.tf`](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.4.2/providers.tf) and that's it. (We've tested this internally, and it works perfectly.)

I do appreciate that this would be a breaking change, and perhaps there should still be consideration for people who will treat this as an off-the-shelf, batteries-included package. I'd imagine people will expect to deploy this manually with minimal code changes (that said, they'll still need to pass in the required arguments anyway...). I'm happy to suggest further ideas around how to make this a non-breaking change, if needs be.

**Comment by stumins** [comment]
Hey @theipster,

Thanks for providing a detailed write-up of your use-case. After some internal deliberation, we are unlikely to add this functionality to AFT.

We recommend performing any IAM actions required by your CI/CD permissions model (such as AssumeRole) inside your pipeline to achieve the necessary CT Management account Administrator-level permissions before deploying AFT.

**Comment by Flydiverny** [comment]
> Hey @theipster,
> 
> Thanks for providing a detailed write-up of your use-case. After some internal deliberation, we are unlikely to add this functionality to AFT.
> 
> We recommend performing any IAM actions required by your CI/CD permissions model (such as AssumeRole) inside your pipeline to achieve the necessary CT Management account Administrator-level permissions before deploying AFT.

What's the reason of why you don't want to do this, and following terraform best practices?

These feels like a very small change to me to allow providers to be properly passed into the module?

I think @theipster's write up here summarizes all the problems well.

We also face these issues and feel like this module and our repository using this module integrates poorly with all or other workflows, both in CI and locally when using both AWS SSO and IAM users with least privileges, where its natural to have providers assume the relevant roles as needed, which terraform handles very well instead of forcing me to manage it manually.

The forced IAM roles are also a bit awkward because it forces us to perform role chaining into IAM roles that must be within the Management / Root account of our organization (due to trust relationships), as an administrator as well. When we have similarly privileged roles in our various AWS accounts that our deployment account and CI/CD flows are able to assume directly. 

Of course it makes sense that you have a recommended way or supported way from your point of view. But locking it down with this semi awkward configuration is unfortunate to me.

**Comment by stumins** [comment]
AFT is intended to be used out-of-box as a top-level module “with batteries included".

Regardless of the CI/CD model used, AFT requires Administrator permissions in the Control Tower management account to deploy necessary resources. AFT makes no assumptions as to how these permissions are provided to the execution environment - any IAM principal with necessary permissions can be used.

Because AFT is a Control Tower based solution, to reduce the effort of deploying AFT, AFT assumes the hub-and-spoke AWSControlTowerExecution role in shared accounts (AFT Mgmt, Logging, Audit) during deployment so that customers are not required to setup a custom role-chaining structure as a prerequisite to using AFT.

I understand that this may conflict with the CI/CD model that your team uses. As mentioned by @theipster, if you want to override these assumptions you can alter or remove the provider.tf file that ships with AFT out-of-box.

**Comment by theipster** [comment]
@stumins To be clear, the idea of removing the `provider.tf` file was my way of proposing how to improve this module.

Asking module users (myself included) to essentially create and maintain our own custom fork of the module with a deleted `provider.tf` means we'll then have extra legwork to do every time we want to upgrade to one of your newer releases.
