### ISSUE TITLE
Default VPCs not being deleted

### ISSUE THREAD

**Issue by CalvinRodo** [aws-ia/terraform-aws-control_tower_account_factory#200]
**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)
1.4.2

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
Terraform v1.2.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.20.1
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

`terraform providers`
```
Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws] > 4.9.0, < 5.0.0
└── module.account_factory_for_terraform
    ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0, < 5.0.0
    ├── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_lambda_layer
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── provider[registry.terraform.io/hashicorp/random]
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_account_provisioning_framework
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_code_repositories
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_customizations
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── provider[registry.terraform.io/hashicorp/local]
    ├── module.aft_feature_options
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_iam_roles
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.audit_service_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.ct_management_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.ct_management_service_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.log_archive_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.log_archive_service_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.aft_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   ├── module.aft_service_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── module.audit_exec_role
    │       └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.aft_account_request_framework
    │   ├── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    │   └── provider[registry.terraform.io/hashicorp/time]
    ├── module.aft_ssm_parameters
    │   └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0
    ├── module.packaging
    │   └── provider[registry.terraform.io/hashicorp/archive]
    └── module.aft_backend
        └── provider[registry.terraform.io/hashicorp/aws] >= 4.9.0

Providers required by state:

    provider[registry.terraform.io/hashicorp/archive]

    provider[registry.terraform.io/hashicorp/random]

    provider[registry.terraform.io/hashicorp/time]

    provider[registry.terraform.io/hashicorp/aws]

    provider[registry.terraform.io/hashicorp/local]
```

**Bug Description**
Newly provisioned accounts have VPCs when `aft_feature_delete_default_vpcs_enabled = true`

**To Reproduce**
1. Provision Account
2. View VPCS in ALL Regions
3. See that default VPCs exist

**Expected behavior**
I expect there to be no default VPCs in all regions of an account

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**
Related to https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/142 but is different because VPC is still in default region

**Comment by adam-daily** [comment]
Hey Calvin,

We've become aware of an issue wherein the Delete Default VPCs feature option is not behaving in a manner that is consistent with AFT documentation. The documentation communicated that the feature option should delete default VPCs in all accounts managed by AFT. In reality AFT deletes default VPCs within the AFT management account, but not in accounts that AFT manages.

While a change to update the behavior to delete VPCs in all AFT vended accounts is relatively straightforward, we've deemed it risky to update to this behavior at this time. Customers have enrolled existing accounts in AFT and have not seen their default VPCs deleted with this feature enabled. Changing the behavior of the feature option to delete those default VPCs could put those customers at risk.

To alleviate the immediate miscommunication, [we've updated the AFT docs to reflect the actual behavior](https://docs.aws.amazon.com/controltower/latest/userguide/aft-feature-options.html#delete-default-vpc-option). We're exploring other options for how to introduce functionality to delete default VPCs in vended accounts in a manner that is safe for our customers. In the meantime, the Control Tower service itself will delete default VPCs in accounts you vend in regions managed by Control Tower. You can read more about this process [here](https://docs.aws.amazon.com/controltower/latest/userguide/configure-without-vpc.html).

We apologize for the inconvenience caused by this miscommunication. Further updates to this behavior will be communicated on the AFT GitHub page and through public AWS documentation.

**Comment by CalvinRodo** [comment]
Thanks for the clear explanation of what was going on, and the guidance on how to resolve this situation within control tower.

**Comment by tuananh** [comment]
I spent this morning going through the code and wonder how the heck can it work? since it's overwritten the client to aft session instead of teh remote account session.
