### ISSUE TITLE
[Question] OU Creation/Update + Enbale Guardrails 

### ISSUE THREAD

**Issue by lliknart** [aws-ia/terraform-aws-control_tower_account_factory#22]
Hi, 
is it possible or already planned to use this module to create and/or enroll new Organizational Unit through AWS Control Tower ?
The only way I see to automate this with Terraform is to create OU independently and then enroll it via AWS Console.
Moreover, is it also planned to enable guardrails on specific OU via this module ?

Thank you

**Comment by adam-daily** [comment]
Hi there, thanks for reaching out. Currently, AFT is not able to create a new OU on its own. You'd need to [create the OU through the Control Tower console](https://docs.aws.amazon.com/controltower/latest/userguide/create-new-ou.html) so that it can properly register with the service.

In terms of running customizations on OUs, yes, you can do that. See documentation [here](https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html) under the **Re-invoke customizations** section for an example that includes running the customizations state machine against a list of OUs.

Going to go ahead and close this issue for now. If anything was unclear or you have further questions, feel free to reopen.
