### ISSUE TITLE
Module "request account" provisioning vpc and subnets automatically with one or more variables

### ISSUE THREAD

**Issue by allanmori** [aws-ia/terraform-aws-control_tower_account_factory#222]
**Describe the outcome you'd like**

Inform parameter or variable with its value and directly through the module "request account" create the new account with VPC and subnets provisioned. Same as when account provisioning for AFT, but for new accounts. 

aft_vpc_cidr
aft_vpc_private_subnet_01_cidr
aft_vpc_private_subnet_02_cidr
aft_vpc_public_subnet_01_cidr
aft_vpc_public_subnet_02_cidr

**Is your feature request related to a problem you are currently experiencing? If so, please describe.**

No

**Additional context**

It's a suggestion/question. I've been looking and haven't found anything. In this case, you would have to provision the VPC and subnets after creating the account. But this could come pre-provisioned automatically. Just as we can do it directly from the console in "Network Configuration".

**Comment by stumins** [comment]
Hey @allanmori,

Thanks for providing us your use case details. We are unlikely to prioritize this feature as part of core AFT due to the wide range of different customer networking use cases and requirements. However, you can create custom VPCs and subnets in your vended accounts with Terraform using the account customization pipelines.

Please see https://github.com/aws-ia/terraform-aws-control_tower_account_factory/tree/main/examples/multiple-account-customizations for an example on re-using a common customization module with multiple account requests.
