### ISSUE TITLE
CodePipeline Broke after AFT upgrade from 1.4 to 1.6

### ISSUE THREAD

**Issue by gavinbul** [aws-ia/terraform-aws-control_tower_account_factory#276]
**Terraform Version & Prov:**

**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)
1.6

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
{Replace me}
```

`terraform providers`
```
{Replace me}
```

**Bug Description**
We upgraded AFT from 1.4 to 1.6 this afternoon. After that, codepipeline, 
xxx-customizations-pipeline, was broken at Pre-API-Helpers stag. I checked codeprojects that aft-global-customizations-api-helpers doesn't exist anymore. 

Here is detail error: 

Error calling startBuild: Project cannot be found: arn:aws:codebuild:us-east-1:xxx:project/aft-global-customizations-api-helpers (Service: AWSCodeBuild; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 23918ab0-35ae-46ac-88b8-19fe1084xxxx; Proxy: null)

**To Reproduce**

**Expected behavior**

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**

**Comment by stumins** [comment]
Hi @gavinbul,

Thanks for opening the issue. [AFT 1.5.0](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.5.0) changed the customization pipelines so that one CodeBuild container is shared between the pre-api-helpers.sh, terraform apply, and post-api-helpers.sh stages. Both per-account and global customization workflows now use this pattern.

As part of this change, behavior was added that re-creates a pipeline in the new form when the pipeline's account is targeted for customization (even if no changes have been made).

Can you please try "Option 2" from https://github.com/aws-ia/terraform-aws-control_tower_account_factory/issues/205 and see if it resolves your issue?
