### ISSUE TITLE
Changing email address breaks invocation for account

### ISSUE THREAD

**Issue by CalvinRodo** [aws-ia/terraform-aws-control_tower_account_factory#282]
**Terraform Version & Prov:**

**AFT Version:**
1.6.2

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
1.1.7
```

`terraform providers`
```
I don't know how to get this from code build
```

**Bug Description**
Changing the email address for an account managed by AFT will break invocation as the email address is not updated in the `aft-request-metadata` dynamodb table

**To Reproduce**
1. Login as root to account you want to update
2. Change email address for account
3. Change email address in aft-account-request repo for that account
4. merge changes
5. invoke customizations on account that was just updated
6. aft-invoke-customizations step machine fails at identify targets step

**Expected behavior**
When updating an email address the email address for the account in `aft-account-metadata` should also be updated

**Related Logs**
Stack Trace for error in `aft-customizations-identify-targets`
```python
[ERROR] KeyError: 'Item'
Traceback (most recent call last):
  File "/var/task/aft_customizations_identify_targets.py", line 62, in lambda_handler
    build_customization_invoke_event_for_target_account(
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 324, in build_customization_invoke_event_for_target_account
    account_request_record = get_account_request_record(
  File "/opt/python/lib/python3.8/site-packages/aft_common/customizations.py", line 290, in get_account_request_record
    item: Dict[str, Any] = response["Item"]
```

**Additional context**
A workaround to this problem is to manually update the email address in the `aft-account-metadata` dynamodb table

**Comment by stumins** [comment]
Hey @CalvinRodo,

This is expected behavior - as mentioned in [the documentation](https://docs.aws.amazon.com/controltower/latest/userguide/aft-update-account.html), AFT does not support changing any of the `control_tower_parameters` other than `ManagedOrganizationalUnit`.

Because changing an account root email address requires authenticating as the root user, it is unlikely that we can add support for changing account emails programmatically to AFT at this time. 

If changing the account email manually, performing the above steps 3 & 4 + the DynamoDB manual record change should get AFT to recognize the new email address.

**Comment by CalvinRodo** [comment]
I'm only opening this issue because I reached out to my AWS Enterprise Support TAM and they reached out internally and I was told to perform the steps I did to cause this issue to occur. 

Hopefully this issue will help the next person who has the same issue in the future.
