### ISSUE TITLE
create_customizations doesn't exist

### ISSUE THREAD

**Issue by sambenj** [aws-ia/terraform-aws-control_tower_account_factory#29]
In https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/sources/aft-customizations-repos/aft-account-request/README.md it states:

`create_customizations must **** be set to true if you intend to customize account after provisioning. Refer to <TODO - insert link Account Customization> documentation for more information.`

However when setting this value, we get the following error:

```
295 | │ Error: Unsupported argument
296 | │
297 | │   on customization_test.tf line 4, in module "customization_test":
298 | │    4:   create_customizations = true
299 | │
300 | │ An argument named "create_customizations" is not expected here.
301 | ╵
```

```
module "customization_test" {
  source = "./modules/aft-account-request"

  create_customizations = true

  control_tower_parameters = {
    AccountEmail = "customizationtest@XXXX.co.uk"
    AccountName  = "customizationtest"
    ManagedOrganizationalUnit = "XXXX"
    SSOUserEmail     = "XXX"
    SSOUserFirstName = "XXX"
    SSOUserLastName  = "XXX"
  }
...
}
```

**Comment by balltrev** [comment]
That's actually a miss in documentation, sorry about that. I believe we've since removed the need for the `create_customizations` parameter, and it should link to https://docs.aws.amazon.com/controltower/latest/userguide/aft-account-customization-options.html where the TODO statement is. 

We will work on getting an update to the README for the aft-account-request section out. Thanks for the catch here @sambenj!

**Comment by balltrev** [comment]
We've updated the README.md here, we ended up just removing the line as we no longer require it at all. Going to close this out for now.
