### ISSUE TITLE
PRE_BUILD State: FAILED  COMMAND_EXECUTION_ERROR Message: Error while executing command: if [ $TF_DISTRIBUTION = "oss" ]; then

### ISSUE THREAD

**Issue by devopscaxsol** [aws-ia/terraform-aws-control_tower_account_factory#384]
Hello

Getting above mentioned error while executing same pipeline for account request.

Below is error message,

<html>
<body>

There are some problems with the configuration, described below.
281 |  
282 | The Terraform configuration must be valid before initialization so that
283 | Terraform can determine which modules and providers need to be installed.
284 |  
285 | Error: Duplicate module call
286 |  
287 | on sandbox_20230814080942.tf line 2:
288 | 2: module "sandbox" {
289 |  
290 | A module call named "sandbox" was already defined at
291 | sandbox_20230814023706.tf:2,1-17. Module calls must have unique names within
292 | a module.
293 |  
294

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by hanafya** [comment]
Hey @devopscaxsol! Please let us know the following information to better troubleshoot the issue:


**Terraform Version & Prov:**

**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
{Replace me}
```

`terraform providers`
```
{Replace me}
```

**Bug Description**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**
Add any other context about the problem here.

Thank you!

**Comment by devopscaxsol** [comment]
Resolved now its misconfiguration...
