### ISSUE TITLE
second time account creation issue

### ISSUE THREAD

**Issue by devopscaxsol** [aws-ia/terraform-aws-control_tower_account_factory#385]
Hello ,

I have created account with AFT one time.

today again trying to follow same scenario but its didnt provisioned?

its been 90 mins since I initiate process.

lambda aft-account-request-processor already process data.

but still lambda aft-controltower-event-logger didnt triggered since last 90 mins.

there was no such errors in logs.

so what will be issue in that?

**Comment by hanafya** [comment]
Hey @devopscaxsol!
Can you tell us a little more about your AFT setup? Please use the following template.

**Terraform Version & Prov:**

**AFT Version:**
(Can be found in the AFT Management Account in the SSM Parameter `/aft/config/aft/version`)

**Terraform Version & Provider Versions**
Please provide the outputs of `terraform version` and `terraform providers` from within your AFT environment

`terraform version`
```
{Replace me}
```

`terraform providers`
```
{Replace me}
```

**Bug Description**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Related Logs**
Provide any related logs or error messages to help explain your problem.

**Additional context**
Add any other context about the problem here.
