### ISSUE TITLE
When provisioning a new account with account request module, nothing is being added to the aft-request-metadata table.

### ISSUE THREAD

**Issue by TaylorRadke** [aws-ia/terraform-aws-control_tower_account_factory#55]

**Comment by TaylorRadke** [comment]
I am able to create accounts with AFT, but when I try to remove them by deleting the account and pushing to github, nothing happens. I am assuming this is because when I initially provisioned the account no metadata was added to the aft-request-metadata table.

**Comment by snebhu3** [comment]
Thank you for reaching out. 
The current expected behavior of AFT is that when you remove an account module from the aft-account-request repository, AFT removes that account from AFT management, however, AFT does not delete the account itself. 
Please may you confirm if this clarifies your question? 

We will also go ahead and create an internal backlog to call this out more explicitly in our [public documentation](https://docs.aws.amazon.com/controltower/latest/userguide/aft-remove-account.html)

**Comment by TaylorRadke** [comment]
This does clarify a misunderstanding I had. Though. Though, I my original issue was that when I provisioned an account there was nothing being added to the ```account-request-metadata``` table, so whenever I tried to re-invoke the customization sfn it would fail to find accounts.

**Comment by balltrev** [comment]
Hey @TaylorRadke, the metadata won't be populated until an account request is completely successful (from a ServiceCatalog perspective). 

My recommended next step would be to look for your AFT vended account in ServiceCatalog and/or inspect CloudWatch logs for the account request processor lambda

**Comment by snebhu3** [comment]
I will go ahead and close this issue for now. 
Please feel free to reach out to us in case of further questions / concerns.
