### ISSUE TITLE
Regression in 1.3.1 - invoke_codebuild_job breaks terraform runs

### ISSUE THREAD

**Issue by lukas-hetzenecker** [aws-ia/terraform-aws-control_tower_account_factory#71]
After an initial terraform apply to AFT 1.3.1, subsequent plans/applys fail with the following error message:

```
module.aft.module.aft_customizations.aws_iam_role_policy.aft_customizations_invoke_account_provisioning_lambda: Refreshing state... [id=aft-customizations-invoke-account-provisioning-role:aft-customizations-invoke-account-provisioning-policy]
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/aft/modules/aft-lambda-layer/lambda.tf line 33, in output "lambda_layer_build_status":
│   33:   value = jsondecode(data.aws_lambda_invocation.invoke_codebuild_job.result)["BuildStatus"]
│     ├────────────────
│     │ data.aws_lambda_invocation.invoke_codebuild_job.result is "{\"Status\": 200}"
│ 
│ The given key does not identify an element in this collection value.
╵
```

This results in a broken state in our terraform pipeline.

Cause for this issue seems to be a mismatch of the name between the [lambda function](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/1.3.1/src/aft_lambda/aft_builder/codebuild_invoker.py#L44) _(Status)_ and the [terraform data resource parsing the result](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/blob/main/modules/aft-lambda-layer/lambda.tf#L33) _(BuildStatus)_

This functionality seems to have been introduced only with AFT 1.3.1.

**Comment by balltrev** [comment]
Thanks for bringing this to our attention @lukas-hetzenecker, we're actively looking into releasing a fix in a new version to fix this regression

**Comment by adam-daily** [comment]
Hey @lukas-hetzenecker, thanks again for bringing up this issue. We're in the midst of a fix which should be released shortly. To make sure we close off on your issue here, can you confirm:

1. The version of Terraform you're using
2. Whether you have any Terraform resources in your build that are consuming the output of the `aft_customizations_invoke_account_provisioning_lambda`
3. Any differences between your deployment of AFT and the standard published AFT mainline code

Just want to make sure we can capture a similar environment to you so we can properly replicate during testing. Thanks again!

**Comment by balltrev** [comment]
We've gone ahead and fixed the key mismatch that you've identified in this release: [1.3.2](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.3.2)

**Comment by lukas-hetzenecker** [comment]
Thank you for the quick response. I can confirm [1.3.2](https://github.com/aws-ia/terraform-aws-control_tower_account_factory/releases/tag/1.3.2) solved this issue.
