### ISSUE TITLE
How to used it in dev mode

### ISSUE THREAD

**Issue by thebigcosinus** [aws-ia/terraform-aws-control_tower_account_factory#88]
Hi,

I find the customization process very long, maybe I'm not doing it well

I commit to my codecommit repo, then I launch the step functions to include my accounts, it tooks ages to deploy (6 code builds per account) it fails( :-) dev mode) and I start the same process again and again.

How can I improve the development build time ? How do you work during build time and AFT ?

Thanks for your help

**Comment by balltrev** [comment]
A common source of deployment slowness is updating the OU an account belongs to. CodeBuild can be slow to provision containers occasionally as well. Frequently our CodeBuild containers take ~1.5-2 min a piece to provision, but are quick to execute.

If you're looking to speed up development times for Terraform itself, you might try to develop/test your customizations in a sandboxed Terraform environment, since AFT is really more geared towards deployment.
