### ISSUE TITLE
Delete default VPC's always fails

### ISSUE THREAD

**Issue by AStrangwood** [aws-ia/terraform-aws-control_tower_account_factory#9]
If you have Control Tower set to specify which regions to govern the lambda that invokes the delete default vpc script will fail with an unauthorized error when it attempts to run against a region that's not governed.

`[ERROR] ClientError: An error occurred (UnauthorizedOperation) when calling the DescribeVpcs operation: You are not authorized to perform this operation.
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 338, in lambda_handler
    vpc = get_default_vpc(client)
  File "/var/task/lambda_function.py", line 37, in get_default_vpc
    response = client.describe_vpcs(
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)`

**Comment by adam-daily** [comment]
Hey, thanks for submitting this issue. Have you enabled [region deny](https://aws.amazon.com/blogs/aws/new-for-aws-control-tower-region-deny-and-guardrails-to-help-you-meet-data-residency-requirements/) for the regions the Lambda is failing for? Just want to make sure I understand the issue.  If that's the case, it's expected that the Lambda would fail for regions where region deny is applied. 

Either way, we'll take an item into our backlog to log and move on if the function is unable to delete a VPC in a region where region deny is applied so that the overall function can succeed. If you haven't enabled region deny for any regions and are still seeing this issue, let us know and we can continue to investigate.

**Comment by AStrangwood** [comment]
Hey, yes I have enabled the region deny functionality you referenced.

**Comment by adam-daily** [comment]
Got ya, thanks for the reply. We made some changes today to log and bypass regions failed due to unauthorized exceptions in this case. When you get a chance, can you update AFT and let us know if that fixed the problem for you?

**Comment by balltrev** [comment]
Please feel free to let us know if you're still having any issues here, going to close this issue in the mean time, thanks!
